frydry_notification_get:
    path: /notification/get
    defaults: { _controller: FryDryNotificationBundle:Notification:get }

frydry_notification_get_list_by_channel:
    path: /notification/get-by-channel
    defaults: { _controller: FryDryNotificationBundle:Notification:getListByChannel }

